server:
  port: 8091
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/internship-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    test-on-borrow: true
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        current_session_context_class: thread
        jdbc.lob.non_contextual_creation: true

  main:
    allow-bean-definition-overriding: true